object Versions {
    const val compose = "1.2.0-alpha07"
    const val hilt = "2.41"
    const val paging = "3.0.1"
    const val lifecycle = "2.4.1"
    const val accompanist = "0.24.6-alpha"
    const val concurrentFuture = "1.1.0"
    const val startup = "1.1.0"
    const val hiltExtension = "1.0.0"
    const val work = "2.7.1"
    const val room = "2.4.2"
    const val moshi = "1.13.0"
    const val retrofit = "2.9.0"
    const val coil = "2.0.0-alpha06"
    const val protobuf = "3.20.0"
}