# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

env:
  ALIAS: ${{ secrets.ALIAS }}
  KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Access GOOGLE_SERVICES_JSON
        run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > ./app/google-services.json

      - name: Generate jks file from base64
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'croissant_key_store.jks'
          fileDir: './'
          encodedString: ${{ secrets.SIGNING_KEY }}

      - name: Generate baseline profile
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          avd-name: baselineProfGenerator
          target: google_apis
          arch: x86_64
          emulator-build: 9322596
          script: ./gradlew :benchmark:connectedBenchmarkAndroidTest -P android.testInstrumentationRunnerArguments.androidx.benchmark.enabledRules=BaselineProfile

      - name: Move generated baseline profile to target folder
        run: mv -f './benchmark/build/outputs/connected_android_test_additional_output/benchmark/connected/baselineProfGenerator(AVD) - 13/BaselineProfileGenerator_generate-baseline-prof.txt' ./app/src/main/baseline-prof.txt

      - name: Check baseline-prof file status
        run: stat ./app/src/main/baseline-prof.txt

      - name: View some lines of baseline-prof file
        run: head ./app/src/main/baseline-prof.txt

      - name: Build with Gradle
        run: ./gradlew assemble

      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease

      - name: Upload Android Release to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.joeloewi.croissant
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: internal
          status: completed
          inAppUpdatePriority: 5
          mappingFile: app/build/outputs/mapping/release/mapping.txt
